apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: artist-service
  description: A Node.js microservice for managing artist profiles and data.
  annotations:
    backstage.io/techdocs-ref: dir:.
  tags:
    - nodejs
    - artist
spec:
  type: service
  lifecycle: production
  owner: artist-relations-team
  system: artist-engagement-portal
  providesApis:
    - artist-api
