apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: my-service
  description: My awesome service
  tags:
    - node
    - backend
spec:
  type: service
  lifecycle: production
  owner: team-a
